# Generated by Django 5.2.5 on 2025-09-02 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RiskCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Risk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cause', models.TextField()),
                ('impact_description', models.TextField()),
                ('likelihood', models.PositiveSmallIntegerField()),
                ('impact', models.PositiveSmallIntegerField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskregister.department')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskregister.riskcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Mitigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strategy', models.CharField(choices=[('accept', 'Accept'), ('transfer', 'Transfer'), ('reduce', 'Reduce'), ('avoid', 'Avoid')], max_length=10)),
                ('action', models.TextField()),
                ('mitigation_date', models.DateField()),
                ('evidence', models.FileField(blank=True, null=True, upload_to='mitigation_evidence/')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitigations', to='riskregister.risk')),
            ],
        ),
        migrations.CreateModel(
            name='RiskOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_owner', to='riskregister.department')),
            ],
        ),
        migrations.AddField(
            model_name='risk',
            name='risk_owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='riskregister.riskowner'),
        ),
        migrations.AlterUniqueTogether(
            name='risk',
            unique_together={('department', 'risk_number')},
        ),
    ]
