# Generated by Django 5.2.5 on 2025-11-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='risk_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
