# Generated by Django 5.2.5 on 2025-11-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0002_alter_risk_risk_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitigation',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mitigation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete')], max_length=20),
        ),
    ]
