# Generated by Django 5.2.5 on 2025-11-19 19:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0003_mitigation_due_date_mitigation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mitigation',
            name='responsible_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='riskregister.riskowner'),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete')], default='pending', max_length=20),
        ),
    ]
