# Generated by Django 5.2.5 on 2025-11-19 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0004_mitigation_responsible_person_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mitigation',
            name='mitigation_date',
        ),
    ]
