# Generated by Django 5.2.5 on 2025-12-04 10:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0006_kpi_alter_risk_options_risk_approved_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-measured_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='riskindicator',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='riskindicator',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='riskindicator',
            name='breach_operator',
            field=models.CharField(choices=[('gt', 'Greater than (>)'), ('gte', 'Greater than or equal (>=)'), ('lt', 'Less than (<)'), ('lte', 'Less than or equal (<=)'), ('eq', 'Equal to (==)')], default='gt', max_length=4),
        ),
        migrations.AddField(
            model_name='riskindicator',
            name='breach_threshold',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='riskindicator',
            name='data_source',
            field=models.CharField(blank=True, help_text='Where to collect the measurement from', max_length=255),
        ),
        migrations.AddField(
            model_name='riskindicator',
            name='direction',
            field=models.CharField(choices=[('increase', 'Higher is worse'), ('decrease', 'Lower is worse')], default='increase', max_length=10),
        ),
        migrations.AddField(
            model_name='riskindicator',
            name='escalation_actions',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='riskindicator',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='riskindicator',
            name='trigger_operator',
            field=models.CharField(choices=[('gt', 'Greater than (>)'), ('gte', 'Greater than or equal (>=)'), ('lt', 'Less than (<)'), ('lte', 'Less than or equal (<=)'), ('eq', 'Equal to (==)')], default='gte', max_length=4),
        ),
        migrations.AddField(
            model_name='riskindicator',
            name='trigger_threshold',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='riskindicator',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='riskindicator',
            name='measurement_period',
            field=models.CharField(default='monthly', max_length=16),
        ),
        migrations.AlterField(
            model_name='riskindicator',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicators', to='riskregister.risk'),
        ),
        migrations.AddIndex(
            model_name='riskindicator',
            index=models.Index(fields=['risk', 'created_at'], name='riskregiste_risk_id_d1615b_idx'),
        ),
        migrations.AddField(
            model_name='indicatormeasurement',
            name='indicator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='riskregister.riskindicator'),
        ),
        migrations.AddIndex(
            model_name='indicatormeasurement',
            index=models.Index(fields=['indicator', 'measured_at'], name='riskregiste_indicat_d28d62_idx'),
        ),
    ]
