# Generated by Django 5.2.5 on 2025-12-07 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0007_indicatormeasurement_alter_riskindicator_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodicMeasurementSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], help_text='How frequently this measurement should be taken', max_length=20)),
                ('scheduled_date', models.DateField(db_index=True, help_text='The date when this measurement is due')),
                ('start_date', models.DateField(help_text='Start of the measurement period')),
                ('end_date', models.DateField(help_text='End of the measurement period')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('overdue', 'Overdue'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_measurements', to=settings.AUTH_USER_MODEL)),
                ('completed_measurement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule', to='riskregister.indicatormeasurement')),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_measurements', to='riskregister.riskindicator')),
            ],
            options={
                'ordering': ['-scheduled_date', 'indicator'],
                'indexes': [models.Index(fields=['indicator', 'scheduled_date'], name='riskregiste_indicat_b2c01e_idx'), models.Index(fields=['status', 'scheduled_date'], name='riskregiste_status_ab0169_idx'), models.Index(fields=['scheduled_date'], name='riskregiste_schedul_384300_idx')],
                'unique_together': {('indicator', 'scheduled_date')},
            },
        ),
    ]
