# Generated by Django 5.2.5 on 2025-12-08 10:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0008_periodicmeasurementschedule'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(db_index=True, default=django.utils.timezone.now, help_text='Date when this assessment was conducted')),
                ('assessment_type', models.CharField(choices=[('initial', 'Initial Assessment'), ('periodic', 'Periodic Review'), ('incident', 'Post-Incident Assessment'), ('mitigation', 'Post-Mitigation Assessment'), ('ad_hoc', 'Ad-Hoc Assessment')], default='periodic', max_length=20)),
                ('likelihood', models.PositiveSmallIntegerField(help_text='Likelihood score (1-5)')),
                ('impact', models.PositiveSmallIntegerField(help_text='Impact score (1-5)')),
                ('previous_likelihood', models.PositiveSmallIntegerField(blank=True, help_text='Likelihood from previous assessment', null=True)),
                ('previous_impact', models.PositiveSmallIntegerField(blank=True, help_text='Impact from previous assessment', null=True)),
                ('rationale', models.TextField(blank=True, help_text='Explanation for the likelihood and impact scores')),
                ('changes_since_last', models.TextField(blank=True, help_text='What has changed since the last assessment')),
                ('evidence', models.TextField(blank=True, help_text='Evidence supporting this assessment')),
                ('recommendations', models.TextField(blank=True, help_text='Recommended actions based on this assessment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_current', models.BooleanField(default=True, help_text='Is this the most recent assessment for this risk?')),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_assessments', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='riskregister.risk')),
            ],
            options={
                'verbose_name': 'Risk Assessment',
                'verbose_name_plural': 'Risk Assessments',
                'ordering': ['-assessment_date', '-created_at'],
                'indexes': [models.Index(fields=['risk', 'assessment_date'], name='riskregiste_risk_id_99d21c_idx'), models.Index(fields=['assessment_date'], name='riskregiste_assessm_d8b3b7_idx'), models.Index(fields=['is_current'], name='riskregiste_is_curr_ed3434_idx')],
            },
        ),
    ]
