# Generated by Django 5.2.5 on 2025-12-14 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0009_riskassessment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicatorAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(db_index=True)),
                ('assessment_period_start', models.DateField(help_text='Start date of the period being assessed')),
                ('assessment_period_end', models.DateField(help_text='End date of the period being assessed')),
                ('measured_value', models.DecimalField(blank=True, decimal_places=6, help_text='The actual measured value', max_digits=18, null=True)),
                ('status', models.CharField(choices=[('on_target', 'On Target'), ('caution', 'Caution'), ('breached', 'Breached'), ('not_measured', 'Not Measured')], default='not_measured', max_length=20)),
                ('is_financial', models.BooleanField(default=False)),
                ('currency_code', models.CharField(blank=True, default='USD', help_text='Currency code (USD, ZWL, EUR, etc.)', max_length=10)),
                ('previous_value', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('variance', models.DecimalField(blank=True, decimal_places=6, help_text='Difference from previous value', max_digits=18, null=True)),
                ('variance_percentage', models.DecimalField(blank=True, decimal_places=4, help_text='Percentage change from previous', max_digits=8, null=True)),
                ('trend', models.CharField(choices=[('improving', 'Improving'), ('stable', 'Stable'), ('deteriorating', 'Deteriorating'), ('new', 'New Assessment')], default='new', max_length=20)),
                ('assessment_notes', models.TextField(blank=True, help_text='Detailed notes about this assessment')),
                ('analysis', models.TextField(blank=True, help_text='Analysis of the results and any variances')),
                ('corrective_actions', models.TextField(blank=True, help_text='Recommended or taken corrective actions')),
                ('evidence_documents', models.FileField(blank=True, help_text='Supporting documentation', null=True, upload_to='indicator_assessments/')),
                ('is_current', models.BooleanField(default=True, help_text='Is this the most recent assessment?')),
                ('reminder_sent', models.BooleanField(default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_assessments', to=settings.AUTH_USER_MODEL)),
                ('indicator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='riskregister.riskindicator')),
                ('measurement', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment', to='riskregister.indicatormeasurement')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='indicator_assessments', to='riskregister.periodicmeasurementschedule')),
            ],
            options={
                'ordering': ['-assessment_date', '-created_at'],
                'indexes': [models.Index(fields=['indicator', 'assessment_date'], name='riskregiste_indicat_45ac52_idx'), models.Index(fields=['status', 'assessment_date'], name='riskregiste_status_1cf754_idx'), models.Index(fields=['is_current', 'indicator'], name='riskregiste_is_curr_0fc1e5_idx')],
                'unique_together': {('indicator', 'assessment_date')},
            },
        ),
    ]
