# Generated by Django 5.2.5 on 2025-12-30 15:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0011_risk_created_at_risk_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='risk',
            name='category',
            field=models.ForeignKey(help_text='Primary category for this risk', on_delete=django.db.models.deletion.CASCADE, to='riskregister.riskcategory'),
        ),
        migrations.CreateModel(
            name='RiskCategoryImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Impact level (1-5) for this category')),
                ('likelihood', models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], help_text='Likelihood level (1-5) for this category')),
                ('notes', models.TextField(blank=True, help_text='Why this risk impacts this category and how')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_impacts', to='riskregister.riskcategory')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_impacts', to='riskregister.risk')),
            ],
            options={
                'verbose_name': 'Risk Category Impact',
                'verbose_name_plural': 'Risk Category Impacts',
                'ordering': ['-impact', '-likelihood', 'category__name'],
                'unique_together': {('risk', 'category')},
            },
        ),
        migrations.AddField(
            model_name='risk',
            name='additional_categories',
            field=models.ManyToManyField(blank=True, help_text='Additional categories this risk affects', related_name='affected_risks', through='riskregister.RiskCategoryImpact', to='riskregister.riskcategory'),
        ),
    ]
