# Generated by Django 6.0 on 2026-01-02 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0012_alter_risk_category_riskcategoryimpact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('re_evaluate', 'Re-evaluate Risk'), ('maintain', 'Maintain Current Risk Rating')], help_text='Whether to re-evaluate the risk or maintain current rating', max_length=20)),
                ('decision_date', models.DateTimeField(auto_now_add=True, help_text='When the decision was made')),
                ('justification', models.TextField(blank=True, help_text='Rationale for the decision, especially if maintaining current rating')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_status', models.CharField(help_text='Status of the assessment at decision time', max_length=20)),
                ('measured_value', models.DecimalField(blank=True, decimal_places=6, help_text='Measured value at decision time', max_digits=18, null=True)),
                ('threshold_breached', models.BooleanField(default=False, help_text='Whether a threshold was breached')),
                ('assessment', models.OneToOneField(help_text='The assessment that requires a decision', on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='riskregister.indicatorassessment')),
                ('decided_by', models.ForeignKey(blank=True, help_text='User who made the decision', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_decisions', to=settings.AUTH_USER_MODEL)),
                ('resulting_risk_assessment', models.ForeignKey(blank=True, help_text='The risk assessment created if decision was to re-evaluate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_by_decision', to='riskregister.riskassessment')),
            ],
            options={
                'verbose_name': 'Assessment Decision',
                'verbose_name_plural': 'Assessment Decisions',
                'ordering': ['-decision_date'],
                'indexes': [models.Index(fields=['assessment', 'decision_date'], name='riskregiste_assessm_10e725_idx'), models.Index(fields=['decision', 'decision_date'], name='riskregiste_decisio_10f5f8_idx'), models.Index(fields=['decided_by', 'decision_date'], name='riskregiste_decided_56b5c0_idx')],
            },
        ),
    ]
