# Generated by Django 6.0 on 2026-01-02 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0013_assessmentdecision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='risk',
            name='additional_categories',
        ),
        migrations.AlterField(
            model_name='risk',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskregister.riskcategory'),
        ),
        migrations.DeleteModel(
            name='RiskCategoryImpact',
        ),
    ]
