# Generated by Django 6.0 on 2026-01-03 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0014_remove_risk_additional_categories_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('object_type', models.CharField(db_index=True, max_length=100)),
                ('object_id', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('context', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='assessmentdecision',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='assessmentdecision',
            name='riskregiste_assessm_10e725_idx',
        ),
        migrations.RemoveIndex(
            model_name='assessmentdecision',
            name='riskregiste_decisio_10f5f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='assessmentdecision',
            name='riskregiste_decided_56b5c0_idx',
        ),
        migrations.AlterField(
            model_name='assessmentdecision',
            name='threshold_breached',
            field=models.BooleanField(default=False, help_text='Whether a threshold was breached at decision time'),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', 'created_at'], name='riskregiste_action_5d1b76_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['object_type', 'object_id'], name='riskregiste_object__07bfb9_idx'),
        ),
    ]
