# Generated by Django 5.2.5 on 2026-01-03 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0015_activitylog_alter_assessmentdecision_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskCategoryImpact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impact', models.PositiveSmallIntegerField()),
                ('likelihood', models.PositiveSmallIntegerField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riskregister.riskcategory')),
                ('risk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_impacts', to='riskregister.risk')),
            ],
            options={
                'verbose_name': 'Risk Category Impact',
                'verbose_name_plural': 'Risk Category Impacts',
                'ordering': ['-impact', '-likelihood', 'category__name'],
                'unique_together': {('risk', 'category')},
            },
        ),
    ]
