# Generated by Django 5.2.5 on 2026-01-04 08:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0016_riskcategoryimpact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mitigation',
            name='completion_percentage',
            field=models.PositiveSmallIntegerField(default=0, help_text='Percentage of mitigation completed (0-100)'),
        ),
        migrations.AddField(
            model_name='mitigation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mitigation',
            name='last_postponed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mitigation',
            name='original_due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mitigation',
            name='postponement_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times this mitigation has been postponed'),
        ),
        migrations.AddField(
            model_name='mitigation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('complete', 'Complete'), ('postponed', 'Postponed'), ('partially_implemented', 'Partially Implemented'), ('not_achieved', 'Not Achieved'), ('cancelled', 'Cancelled')], default='pending', max_length=30),
        ),
        migrations.AlterField(
            model_name='mitigation',
            name='strategy',
            field=models.CharField(choices=[('accept', 'Accept'), ('transfer', 'Transfer'), ('reduce', 'Reduce'), ('avoid', 'Avoid')], max_length=30),
        ),
        migrations.CreateModel(
            name='MitigationProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('created', 'Mitigation Created'), ('status_change', 'Status Changed'), ('postponed', 'Postponed'), ('partial_completion', 'Partial Completion'), ('due_date_extended', 'Due Date Extended'), ('responsibility_changed', 'Responsibility Changed'), ('evidence_added', 'Evidence Added'), ('progress_update', 'Progress Update'), ('completion_failed', 'Completion Failed'), ('cancelled', 'Cancelled'), ('resumed', 'Resumed')], max_length=30)),
                ('notes', models.TextField(blank=True, help_text='Detailed notes about this action')),
                ('status_at_time', models.CharField(blank=True, help_text='Mitigation status at the time of this log entry', max_length=30)),
                ('previous_status', models.CharField(blank=True, help_text='Previous status before this change', max_length=30)),
                ('completion_percentage', models.PositiveSmallIntegerField(default=0, help_text='Completion percentage at time of log (0-100)')),
                ('previous_completion_percentage', models.PositiveSmallIntegerField(default=0, help_text='Previous completion percentage')),
                ('due_date_at_time', models.DateField(blank=True, null=True)),
                ('previous_due_date', models.DateField(blank=True, null=True)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='mitigation_progress_evidence/')),
                ('postponement_reason', models.TextField(blank=True, help_text='Reason for postponement (if applicable)')),
                ('new_target_date', models.DateField(blank=True, help_text='New target date after postponement', null=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for not achieving mitigation (if applicable)')),
                ('lessons_learned', models.TextField(blank=True, help_text='Lessons learned from partial/failed implementation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mitigation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_logs', to='riskregister.mitigation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mitigation_progress_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mitigation Progress Log',
                'verbose_name_plural': 'Mitigation Progress Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mitigation', 'created_at'], name='riskregiste_mitigat_0a463f_idx'), models.Index(fields=['action_type', 'created_at'], name='riskregiste_action__27d834_idx')],
            },
        ),
    ]
