# Generated by Django 5.2.5 on 2026-01-04 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0017_mitigation_completion_percentage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('enable_in_app_notifications', models.BooleanField(default=True)),
                ('notification_frequency', models.CharField(choices=[('immediate', 'Immediate'), ('daily_digest', 'Daily Digest'), ('twice_daily', 'Twice Daily'), ('weekly', 'Weekly')], default='immediate', max_length=20)),
                ('minimum_risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', help_text='Only receive notifications for risks at or above this level', max_length=20)),
                ('notify_mitigation_due', models.BooleanField(default=True, help_text='Mitigations due soon')),
                ('notify_assessment_schedule', models.BooleanField(default=True, help_text='Assessment schedules')),
                ('notify_risk_changes', models.BooleanField(default=True, help_text='Risk level changes')),
                ('notify_indicator_breach', models.BooleanField(default=True, help_text='Indicator breaches')),
                ('days_before_due_mitigation', models.IntegerField(default=7, help_text='Days before mitigation due date to notify')),
                ('days_before_due_assessment', models.IntegerField(default=3, help_text='Days before assessment due date to notify')),
                ('quiet_hours_start', models.TimeField(blank=True, help_text='Start of quiet hours (no notifications)', null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, help_text='End of quiet hours', null=True)),
                ('last_daily_digest_sent', models.DateTimeField(blank=True, null=True)),
                ('last_weekly_digest_sent', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Rule name for identification', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of this rule')),
                ('rule_type', models.CharField(choices=[('mitigation_due', 'Mitigation Due Date'), ('assessment_schedule', 'Assessment Schedule'), ('risk_level', 'Risk Level Change'), ('indicator_breach', 'Indicator Breach')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.IntegerField(default=0, help_text='Higher priority rules are processed first')),
                ('condition', models.CharField(choices=[('overdue', 'Is Overdue'), ('due_in_days', 'Due in X Days'), ('risk_high', 'Risk Level is High'), ('risk_critical', 'Risk Level is Critical'), ('overdue_days', 'Overdue by X Days'), ('no_assessment', 'No Assessment for X Days')], max_length=50)),
                ('condition_value', models.IntegerField(blank=True, help_text='Numeric value for conditions (e.g., days)', null=True)),
                ('risk_level_filter', models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], help_text='Only trigger for risks at this level (leave blank for all)', max_length=20)),
                ('recipient_type', models.CharField(choices=[('risk_owner', 'Risk Owner'), ('mitigation_responsible', 'Mitigation Responsible Person'), ('department_head', 'Department Head'), ('all_managers', 'All Managers'), ('specific_user', 'Specific User')], max_length=50)),
                ('notify_via_email', models.BooleanField(default=True)),
                ('notify_in_app', models.BooleanField(default=True)),
                ('message_template', models.TextField(help_text='Use {risk_title}, {due_date}, {days}, {responsible_person} as placeholders')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_rules', to=settings.AUTH_USER_MODEL)),
                ('specific_user', models.ForeignKey(blank=True, help_text="Required if recipient_type is 'specific_user'", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notification_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Rule',
                'verbose_name_plural': 'Notification Rules',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('mitigation_due', 'Mitigation Due'), ('mitigation_overdue', 'Mitigation Overdue'), ('assessment_due', 'Assessment Due'), ('assessment_overdue', 'Assessment Overdue'), ('risk_level_change', 'Risk Level Change'), ('indicator_breach', 'Indicator Breach'), ('general', 'General Notification')], max_length=50)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('action_url', models.CharField(blank=True, help_text='Link to take action', max_length=500)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('is_emailed', models.BooleanField(default=False)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Notification auto-dismisses after this date', null=True)),
                ('indicator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riskregister.riskindicator')),
                ('mitigation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riskregister.mitigation')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('risk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riskregister.risk')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='riskregister.periodicmeasurementschedule')),
                ('generated_by_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_notifications', to='riskregister.notificationrule')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read', '-created_at'], name='riskregiste_recipie_7ae3d6_idx'), models.Index(fields=['notification_type', 'created_at'], name='riskregiste_notific_cf5ae2_idx')],
            },
        ),
    ]
