# Generated by Django 5.2.5 on 2026-01-07 02:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0018_notificationpreference_notificationrule_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskindicator',
            name='appetite_tolerance_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10),
        ),
    ]
