# Generated by Django 5.2.5 on 2026-01-07 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0019_alter_riskindicator_appetite_tolerance_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='indicatorassessment',
            name='triggered_risk_assessment',
            field=models.BooleanField(default=False, help_text='Whether this assessment triggered a full risk reassessment'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='aggregate_status',
            field=models.CharField(blank=True, choices=[('on_target', 'On Target'), ('caution', 'Caution'), ('breached', 'Breached'), ('mixed', 'Mixed Results'), ('none', 'No Indicators')], help_text='Overall status aggregated from indicator assessments', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='executive_summary',
            field=models.TextField(blank=True, help_text='High-level summary for executive reports'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='indicators_breached',
            field=models.IntegerField(default=0, help_text='Number of indicators breached'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='indicators_in_caution',
            field=models.IntegerField(default=0, help_text='Number of indicators in caution zone'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='indicators_on_target',
            field=models.IntegerField(default=0, help_text='Number of indicators on target'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='key_findings',
            field=models.JSONField(blank=True, default=list, help_text='Structured key findings from indicator assessments'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='source_indicator_assessments',
            field=models.ManyToManyField(blank=True, help_text='Indicator assessments that informed this risk assessment', related_name='resulting_risk_assessments', to='riskregister.indicatorassessment'),
        ),
        migrations.CreateModel(
            name='AssessmentScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_assessment_frequency', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual')], default='quarterly', help_text='How often to conduct full risk assessments', max_length=20)),
                ('min_indicator_assessments', models.IntegerField(default=1, help_text='Minimum number of indicator assessments required')),
                ('auto_trigger_on_breached', models.IntegerField(default=2, help_text='Auto-trigger risk assessment when this many indicators breach')),
                ('schedule_advance_months', models.IntegerField(default=12, help_text='Generate schedules this many months in advance')),
                ('last_generated', models.DateField(blank=True, help_text='Last date schedules were generated', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether automatic scheduling is active for this risk')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_config', to='riskregister.risk')),
            ],
            options={
                'verbose_name': 'Assessment Schedule Configuration',
                'verbose_name_plural': 'Assessment Schedule Configurations',
            },
        ),
    ]
