# Generated by Django 5.2.5 on 2026-01-07 07:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0020_indicatorassessment_triggered_risk_assessment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='overall_rationale',
            field=models.TextField(blank=True, help_text='Overall rationale explaining the final risk evaluation'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='overall_result',
            field=models.TextField(blank=True, help_text='Overall assessment result/conclusion'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_progress', 'In Progress'), ('pending_indicators', 'Pending Indicators'), ('completed', 'Completed'), ('approved', 'Approved')], default='draft', help_text='Current status of the assessment', max_length=20),
        ),
        migrations.AddField(
            model_name='riskindicator',
            name='indicator_rationale',
            field=models.TextField(blank=True, help_text="Rationale/comments for this indicator's assessment result"),
        ),
        migrations.AddField(
            model_name='riskindicator',
            name='indicator_result',
            field=models.TextField(blank=True, help_text='Result/outcome of this specific indicator assessment'),
        ),
        migrations.AddField(
            model_name='riskindicator',
            name='risk_assessment',
            field=models.ForeignKey(blank=True, help_text='The risk assessment this indicator belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_indicators', to='riskregister.riskassessment'),
        ),
        migrations.AddField(
            model_name='riskindicator',
            name='scheduled_assessment_date',
            field=models.DateField(blank=True, help_text='Scheduled date for assessing this indicator (must be <= parent assessment date)', null=True),
        ),
        migrations.AddField(
            model_name='riskindicator',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Assessment'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='draft', help_text='Current status of this indicator assessment', max_length=20),
        ),
    ]
