# Generated by Django 5.2.5 on 2026-01-12 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0021_riskassessment_overall_rationale_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AssessmentDecision',
        ),
    ]
