# Generated by Django 5.2.5 on 2026-01-30 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0023_inherent_risk_and_controls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riskowner',
            name='user',
            field=models.OneToOneField(blank=True, help_text='Link to Django user account for login access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_owner_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
