# Generated by Django 6.0 on 2026-02-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0028_add_expiry_date_to_notificationpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationpreference',
            name='frequency',
            field=models.CharField(choices=[('immediate', 'Immediate'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly')], default='daily', max_length=20),
        ),
        migrations.AlterField(
            model_name='notificationpreference',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
