# Generated by Django 6.0 on 2026-03-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riskregister', '0029_alter_notificationpreference_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskcategory',
            name='weight',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=5, help_text='Importance weight for this category (1-10)'),
        ),
    ]
